'use strict';

const assert = require('assert');

class MockRange {
  constructor(sheet, row, column, numRows, numColumns) { Object.assign(this, { sheet, row, column, numRows, numColumns }); }
  getValues() { const rows=[]; for(let r=0;r<this.numRows;r+=1){const values=[];for(let c=0;c<this.numColumns;c+=1)values.push(this.sheet.getCell(this.row+r,this.column+c));rows.push(values);}return rows; }
  getDisplayValues(){return this.getValues().map((row)=>row.map((value)=>value instanceof Date?value.toISOString():value==null?'':String(value)));}
  setValues(values){assert.strictEqual(values.length,this.numRows,'setValues row count mismatch');values.forEach((row,r)=>{assert.strictEqual(row.length,this.numColumns,'setValues column count mismatch');row.forEach((value,c)=>this.sheet.setCell(this.row+r,this.column+c,value));});return this;}
}
class MockSheet {
  constructor(name,grid){this.name=name;this.grid=grid.map((row)=>row.slice());}
  getName(){return this.name;}
  getLastRow(){let last=0;this.grid.forEach((row,index)=>{if(row.some((v)=>v!==''&&v!=null))last=index+1;});return last;}
  getLastColumn(){let last=0;this.grid.forEach((row)=>row.forEach((v,index)=>{if(v!==''&&v!=null)last=Math.max(last,index+1);}));return last;}
  getMaxRows(){return 20000;} getRange(row,column,numRows=1,numColumns=1){return new MockRange(this,row,column,numRows,numColumns);}
  getCell(row,column){return this.grid[row-1]&&this.grid[row-1][column-1]!==undefined?this.grid[row-1][column-1]:'';}
  setCell(row,column,value){while(this.grid.length<row)this.grid.push([]);while(this.grid[row-1].length<column)this.grid[row-1].push('');this.grid[row-1][column-1]=value;}
  deleteRow(row){this.grid.splice(row-1,1);}
}
class MockSpreadsheet{constructor(name,sheets){this.name=name;this.sheets=sheets;}getName(){return this.name;}getSheetByName(name){return this.sheets[name]||null;}}

const headers={
Templates:['Template ID','Template Name','Touch Number','Active','Subject','Plain-Text Body','HTML Body','Last Updated','Approved By','Notes'],
Employers:['Employer ID','Company Name','Website','Industry','Headquarters Address','Headquarters City','Headquarters State','Headquarters ZIP','Headquarters County','Main Phone','NJ Location Count','Relationship Stage','Assigned To','Prospect Source','Source URL','Date Added','Last Contact','Active','Notes'],
Locations:['Location ID','Employer ID','Company Name','Location Name','Street Address','City','State','ZIP','County','County Source','County Confidence','Main Phone','Active','Notes'],
Contacts:['Contact ID','Employer ID','Company Name','First Name','Last Name','Title','Email','Phone','Location ID','Worksite County','Email Verified','Verified Date','Contact Source','Relationship / Consent','Do Not Contact','Last Contact','Notes'],
'Campaign Queue':['Queue ID','Campaign ID','Employer ID','Contact ID','Company Name','Contact Name','Email','Worksite County','Job Family','Template ID','Subject','Scheduled Date','Scheduled Time','Touch Number','Priority','Approval Status','Send Status','Sent At','Gmail Thread ID','Gmail Message ID','Reply Received','Stop Sequence','Error / Notes'],
'Email Activity':['Event ID','Timestamp','Queue ID','Campaign ID','Employer ID','Contact ID','Email','Event Type','Gmail Thread ID','Gmail Message ID','Details','Processed'],
Replies:['Reply ID','Received At','Employer ID','Contact ID','Company Name','Contact Email','Gmail Thread ID','Subject','Original Reply','Clean Reply','Primary Classification','Positive','Hiring Now','Future Hiring','Entry Level','Internship','Apprenticeship','Worksite City','Worksite ZIP','County','County Source','Job Type(s)','Openings','Welding Processes','Experience','Certifications','Shift','Pay','Benefits','Hiring Date','Preferred Next Step','Hiring Contact','Phone','Additional Information','Extraction Confidence','Human Review Status','Assigned To','Outreach Email','Queue ID','Archive ID','Processing Status','Test Run ID','Gmail Message ID','Processing Error'],
Leads:['Lead ID','Employer ID','Company Name','Primary Contact','Email','Phone','Worksite County','Lead Stage','Lead Type','Job Type(s)','Openings','Entry Level','Internship','Apprenticeship','Hiring Timeframe','Assigned To','First Positive Reply','Last Activity','Next Action','Follow-Up Date','Lead Score','Review Status','Notes'],
'Job Opportunities':['Opportunity ID','Lead ID','Employer ID','Company Name','Original Job Title','Standard Job Type','Career Level','Welding Process(es)','Openings','Employment Type','Entry Level','Internship','Apprenticeship','Experience Required','Certifications','Worksite Address','City','ZIP','County','County Source','Shift','Pay Min','Pay Max','Pay Type','Benefits','Anticipated Start','Application Method','Application Contact','Permission to Share','Status','Date Received','Last Confirmed','Expiration Review Date','Source Reply ID','Notes'],
'Follow-Ups':['Task ID','Lead ID','Employer ID','Company Name','Contact','Task Type','Due Date','Due Time','Priority','Owner','Status','Draft Subject','Draft Body','Gmail Draft ID','Completed At','Notes'],
Suppressions:['Suppression ID','Email','Employer ID','Company Name','Reason','Source','Date Added','Permanent','Notes'],
'Automation Log':['Log ID','Timestamp','Process','Status','Records Checked','Records Changed','Messages Sent','Errors','Duration Seconds','Details'],
'Reply Archive':['Archive ID','Created At','Source Message ID','Source Thread ID','Source RFC Message ID','Source Reply ID','Queue ID','Contact ID','Employer ID','Company Name','Contact Email','Subject','Body Type','Body Content']
};
const configurationRows=[['NJCWWA Employer Outreach Automation Configuration','','',''],['','','',''],['Setting','Value','Purpose','Change Control'],['Sender Email','weldingworkforcealliance@gmail.com','','Locked'],['Daily New Outreach Target',100,'','Locked'],['Daily Total Send Cap',100,'','Admin'],['Business Days Only','Yes','','Admin'],['Time Zone','America/New_York','','Locked'],['Send Window Start','9:30 AM','','Admin'],['Send Window End','4:30 PM','','Admin'],['Messages Per Batch',10,'','Admin'],['Minutes Between Batches',45,'','Admin'],['Follow-Up 1 Delay',5,'','Admin'],['Follow-Up 2 Delay',10,'','Admin'],['Maximum Follow-Ups',0,'','Locked'],['Stop on Reply','Yes','','Locked'],['Stop on Unsubscribe','Yes','','Locked'],['Require Approved Status','Yes','','Locked'],['Require Unique Email','Yes','','Locked'],['Campaign Enabled','No','','Locked'],['Test Mode','Yes','','Locked'],['Test Recipient Allowlist','weldingworkforcealliance@gmail.com, grimmdriver@gmail.com','','Admin'],['Physical Mailing Address','REQUIRED BEFORE LIVE LAUNCH','','Locked'],['Employer Hiring Form URL','TBD','','Admin'],['Alliance Website','TBD','','Admin'],['Default Lead Owner','Richard Genco','','Admin'],['Live Launch Authorized','No','','Locked'],['Campaign Start Date','2026-10-05','','Locked'],['Campaign End Date','2026-10-09','','Locked']];
const sheets={Configuration:new MockSheet('Configuration',configurationRows),Templates:new MockSheet('Templates',[headers.Templates,['TPL-INITIAL','Initial',1,'Yes','Hiring welders?','Hello {{FirstName}},\n\nIs {{CompanyName}} hiring?','','','','']]),Employers:new MockSheet('Employers',[headers.Employers,['TEST-E1','Test Fabrication Co.','','Welding / metal fabrication','','','','','Middlesex','','','Needs Review','Richard Genco','','','','','Yes','']]),Locations:new MockSheet('Locations',[headers.Locations]),Contacts:new MockSheet('Contacts',[headers.Contacts,['TEST-C1','TEST-E1','Test Fabrication Co.','Jane','Smith','HR','hr@testfabrication.example','732-555-0101','','Middlesex','Unknown','','','Public business listing','No','','PUBLIC EMAIL CONFIRMED']]),'Campaign Queue':new MockSheet('Campaign Queue',[headers['Campaign Queue'],['TEST-Q1','TEST-CAMPAIGN','TEST-E1','TEST-C1','Test Fabrication Co.','Jane Smith','hr@testfabrication.example','Middlesex','MIG/GMAW Welder','TPL-INITIAL','Hiring welders?',new Date('2026-10-04T12:30:00Z'),'8:30 AM',1,'High','Approved','Sent',new Date('2026-10-04T12:30:00Z'),'THREAD-1','SENT-1','No','No','']]),'Email Activity':new MockSheet('Email Activity',[headers['Email Activity']]),Replies:new MockSheet('Replies',[headers.Replies]),Leads:new MockSheet('Leads',[headers.Leads]),'Job Opportunities':new MockSheet('Job Opportunities',[headers['Job Opportunities']]),'Follow-Ups':new MockSheet('Follow-Ups',[headers['Follow-Ups']]),Suppressions:new MockSheet('Suppressions',[headers.Suppressions]),'Automation Log':new MockSheet('Automation Log',[headers['Automation Log']]),'Reply Archive':new MockSheet('Reply Archive',[headers['Reply Archive']])};
module.exports={assert,MockSpreadsheet,sheets};
