import { createClient } from 'npm:@supabase/supabase-js@2';

type ClaimedQueue = {
  queue_id: string;
  session_id: string;
  recipient_email: string;
  attempts: number;
};

type AttendanceSession = {
  id: string;
  pair_id: string;
  attendance_date: string;
  instructor_notes: string | null;
  finalized_at: string | null;
  finalized_by: string | null;
};

type AttendancePair = {
  id: string;
  pair_name: string;
  attendance_mode: string;
};

type AttendanceRecord = {
  student_id: string;
  initial_status: string | null;
  final_status: string | null;
  completion_flags: string[] | null;
  notes: string | null;
};

type Student = {
  id: string;
  display_name: string;
  external_student_id: string | null;
};

function escapeHtml(value: unknown) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function labelStatus(value: string | null) {
  if (!value) return 'Not recorded';
  return value
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function labelFlag(value: string) {
  if (value === 'disappeared') return 'Student disappeared';
  return labelStatus(value);
}

function buildEmailHtml(args: {
  pair: AttendancePair;
  session: AttendanceSession;
  records: AttendanceRecord[];
  students: Student[];
}) {
  const studentMap = new Map(args.students.map((student) => [student.id, student]));
  const sorted = [...args.records].sort((a, b) => {
    const left = studentMap.get(a.student_id)?.display_name ?? '';
    const right = studentMap.get(b.student_id)?.display_name ?? '';
    return left.localeCompare(right);
  });

  const rows = sorted
    .map((record) => {
      const student = studentMap.get(record.student_id);
      const flags = (record.completion_flags ?? []).map(labelFlag).join(', ') || 'None';
      return `
        <tr>
          <td>${escapeHtml(student?.display_name || 'Student')}</td>
          <td>${escapeHtml(labelStatus(record.initial_status))}</td>
          <td>${escapeHtml(labelStatus(record.final_status || record.initial_status))}</td>
          <td>${escapeHtml(flags)}</td>
          <td>${escapeHtml(record.notes || '')}</td>
        </tr>`;
    })
    .join('');

  return `<!doctype html>
  <html>
    <body style="font-family:Arial,Helvetica,sans-serif;color:#17201f;background:#f3f6f5;padding:24px;">
      <div style="max-width:900px;margin:0 auto;background:#fff;border:1px solid #d7dfdd;border-radius:10px;padding:22px;">
        <h1 style="margin:0 0 6px;font-size:24px;">PVHS Daily Attendance Report</h1>
        <p style="margin:0 0 18px;color:#596864;">
          <strong>${escapeHtml(args.pair.pair_name)}</strong> · ${escapeHtml(args.session.attendance_date)}
        </p>
        <table style="border-collapse:collapse;width:100%;font-size:13px;">
          <thead>
            <tr style="background:#eef3f1;text-align:left;">
              <th style="padding:9px;border:1px solid #d7dfdd;">Student</th>
              <th style="padding:9px;border:1px solid #d7dfdd;">Initial</th>
              <th style="padding:9px;border:1px solid #d7dfdd;">Final</th>
              <th style="padding:9px;border:1px solid #d7dfdd;">Flags</th>
              <th style="padding:9px;border:1px solid #d7dfdd;">Instructor Note</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
        ${args.session.instructor_notes ? `<p style="margin-top:18px;"><strong>Class note:</strong> ${escapeHtml(args.session.instructor_notes)}</p>` : ''}
        <p style="margin-top:20px;color:#72807c;font-size:11px;">
          Generated by the Living Teacher Guide attendance system from the finalized attendance record.
        </p>
      </div>
    </body>
  </html>`;
}

async function sendResendEmail(args: {
  apiKey: string;
  from: string;
  to: string;
  subject: string;
  html: string;
}) {
  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${args.apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: args.from,
      to: [args.to],
      subject: args.subject,
      html: args.html,
    }),
  });

  const body = await response.text();
  if (!response.ok) {
    throw new Error(`Resend ${response.status}: ${body.slice(0, 500)}`);
  }
  return body;
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  const expectedSecret = Deno.env.get('ATTENDANCE_CRON_SECRET') ?? '';
  const suppliedSecret = req.headers.get('x-attendance-cron-secret') ?? '';
  if (!expectedSecret || suppliedSecret !== expectedSecret) {
    return new Response('Unauthorized', { status: 401 });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const resendApiKey = Deno.env.get('RESEND_API_KEY');
  const attendanceFromEmail = Deno.env.get('ATTENDANCE_FROM_EMAIL');

  if (!supabaseUrl || !serviceRoleKey || !resendApiKey || !attendanceFromEmail) {
    return Response.json(
      { error: 'Attendance report worker is missing required server-side configuration.' },
      { status: 500 }
    );
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: claimed, error: claimError } = await supabase.rpc(
    'claim_due_attendance_reports',
    { p_limit: 25 }
  );

  if (claimError) {
    return Response.json({ error: claimError.message }, { status: 500 });
  }

  const queueRows = (claimed ?? []) as ClaimedQueue[];
  const results: Array<{ queue_id: string; status: 'sent' | 'failed'; error?: string }> = [];

  for (const queue of queueRows) {
    try {
      const { data: sessionData, error: sessionError } = await supabase
        .from('attendance_sessions')
        .select('id,pair_id,attendance_date,instructor_notes,finalized_at,finalized_by')
        .eq('id', queue.session_id)
        .maybeSingle();
      if (sessionError) throw sessionError;
      if (!sessionData) throw new Error('Attendance session not found');
      const session = sessionData as AttendanceSession;
      if (!session.finalized_at) throw new Error('Attendance session is not finalized');

      const [{ data: pairData, error: pairError }, { data: recordData, error: recordError }] =
        await Promise.all([
          supabase
            .from('attendance_pairs')
            .select('id,pair_name,attendance_mode')
            .eq('id', session.pair_id)
            .maybeSingle(),
          supabase
            .from('attendance_records')
            .select('student_id,initial_status,final_status,completion_flags,notes')
            .eq('session_id', session.id),
        ]);

      if (pairError) throw pairError;
      if (recordError) throw recordError;
      if (!pairData) throw new Error('Attendance pair not found');
      const pair = pairData as AttendancePair;
      if (pair.attendance_mode !== 'pvhs') throw new Error('Queue item is not a PVHS attendance report');

      const records = (recordData ?? []) as AttendanceRecord[];
      const studentIds = records.map((record) => record.student_id);
      let students: Student[] = [];
      if (studentIds.length) {
        const { data: studentData, error: studentError } = await supabase
          .from('attendance_students')
          .select('id,display_name,external_student_id')
          .in('id', studentIds);
        if (studentError) throw studentError;
        students = (studentData ?? []) as Student[];
      }

      const html = buildEmailHtml({ pair, session, records, students });
      await sendResendEmail({
        apiKey: resendApiKey,
        from: attendanceFromEmail,
        to: queue.recipient_email,
        subject: `PVHS Attendance Report · ${pair.pair_name} · ${session.attendance_date}`,
        html,
      });

      const { error: sentError } = await supabase
        .from('attendance_report_queue')
        .update({ status: 'sent', sent_at: new Date().toISOString(), last_error: null })
        .eq('id', queue.queue_id)
        .eq('status', 'processing');
      if (sentError) throw sentError;

      results.push({ queue_id: queue.queue_id, status: 'sent' });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      await supabase
        .from('attendance_report_queue')
        .update({ status: 'failed', last_error: message.slice(0, 2000) })
        .eq('id', queue.queue_id);
      results.push({ queue_id: queue.queue_id, status: 'failed', error: message });
    }
  }

  return Response.json({ claimed: queueRows.length, results });
});
