"""Generate an idempotent LTG draft-guide import for the two additional Level 1 pairs.

Committee syllabus outcomes and grades are stored as locked draft curriculum.
This deliberately does not activate sections, enroll students, or approve a syllabus.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    ROOT / "docs/WLD114_NIGHT_LEVEL1_22_DAY_PAYLOAD.json",
    ROOT / "docs/WLD115_NIGHT_LEVEL1_22_DAY_PAYLOAD.json",
    ROOT / "docs/WLD120_SPRING6A_24_DAY_PAYLOAD.json",
    ROOT / "docs/WLD150_SPRING6A_24_DAY_PAYLOAD.json",
]
OUTPUT = ROOT / "supabase/migrations/20260923110000_additional_level1_pair_draft_guides.sql"

guides = []
for path in SOURCES:
    payload = json.loads(path.read_text())
    minutes = payload["section_time"]["minutes"]
    days = []
    for day in payload["days"]:
        segments = day["segments"]
        assert sum(segment["planned_minutes"] for segment in segments) == minutes
        assert segments[0]["start_minute"] == 0 and segments[-1]["end_minute"] == minutes
        days.append({key: day.get(key) for key in (
            "planner_day_number", "title", "objective", "instructor_prep", "safety_focus",
            "opening_review", "demonstration", "guided_practice", "independent_practice",
            "instructor_checks", "assessment", "teaching_tips", "materials_equipment",
            "evidence_check_for_understanding", "outcome_codes", "segments")})
    assert len(days) == payload["planned_instructional_days"]
    guides.append({
        "course_code": payload["course_code"],
        "guide_name": payload["guide_name"],
        "planned_instructional_days": len(days),
        "protected_outcomes": payload["protected_outcomes_from_supplied_syllabus"],
        "grade_weights": payload["grade_weights_from_supplied_syllabus"],
        "days": days,
    })

assert {x["course_code"] for x in guides} == {"WLD 114", "WLD 115", "WLD 120", "WLD 150"}
assert [len(x["protected_outcomes"]) for x in guides] == [7, 6, 7, 6]
assert all(sum(x["grade_weights"].values()) == 100 for x in guides)
data = json.dumps(guides, ensure_ascii=False, separators=(",", ":"))
assert "$ltg_json$" not in data

sql = """-- Import four additional Level 1 curriculum guides as drafts.
-- Committee-syllabus outcomes and grading are stored as locked draft curriculum.
-- No sections, attendance pairs, student data, gradebooks, or approvals are created.
-- Spring 2027 meeting dates are provisional and belong in a later section release.
-- Generated by scripts/build-additional-level1-guides-sql.py.

do $ltg$
declare
  bundle jsonb := $ltg_json$DATA$ltg_json$::jsonb;
  guide jsonb;
  day_record jsonb;
  segment_record jsonb;
  course_record record;
  guide_id uuid;
  guide_day_id uuid;
  target_curriculum_id uuid;
begin
  for guide in select value from jsonb_array_elements(bundle) loop
    select id, school_id into strict course_record
    from public.courses
    where course_code = guide->>'course_code'
      and school_id = '08ccb452-83ab-482f-bb28-5576e02741b2'::uuid;

    insert into public.course_guides
      (school_id, course_id, guide_name, academic_year, version_label,
       planned_instructional_days, status)
    values
      (course_record.school_id, course_record.id, guide->>'guide_name',
       '2026-2027', '2026-09-23-additional-L1-v1',
       (guide->>'planned_instructional_days')::integer, 'draft')
    on conflict (school_id, course_id, academic_year, version_label)
    do update set guide_name = excluded.guide_name,
                  planned_instructional_days = excluded.planned_instructional_days,
                  status = 'draft', updated_at = now()
    returning id into guide_id;

    delete from public.course_guide_days where guide_id = guide_id;

    select id into target_curriculum_id
    from public.course_curriculum
    where course_id = course_record.id
      and version = '2026-2027 additional Level 1 committee syllabus draft'
    limit 1;
    if target_curriculum_id is null then
      insert into public.course_curriculum
        (school_id, course_id, version, curriculum_text, status, locked)
      values
        (course_record.school_id, course_record.id,
         '2026-2027 additional Level 1 committee syllabus draft',
         jsonb_build_object('source', 'user supplied 2026-27 curriculum committee syllabus',
                            'grade_weights', guide->'grade_weights')::text,
         'draft', true)
      returning id into target_curriculum_id;
    end if;
    delete from public.course_outcomes where curriculum_id = target_curriculum_id;
    insert into public.course_outcomes
      (school_id, course_id, curriculum_id, outcome_code, outcome_text, locked)
    select course_record.school_id, course_record.id, target_curriculum_id,
           key, value, true
    from jsonb_each_text(guide->'protected_outcomes');

    for day_record in select value from jsonb_array_elements(guide->'days') loop
      insert into public.course_guide_days
        (school_id, course_id, guide_id, planner_day_number, title, objective,
         instructor_prep, safety_focus, opening_review, demonstration,
         guided_practice, independent_practice, instructor_checks, assessment,
         teaching_tips, materials_equipment, evidence_check_for_understanding)
      values
        (course_record.school_id, course_record.id, guide_id,
         (day_record->>'planner_day_number')::integer,
         day_record->>'title', day_record->>'objective',
         day_record->>'instructor_prep', day_record->>'safety_focus',
         day_record->>'opening_review', day_record->>'demonstration',
         day_record->>'guided_practice', day_record->>'independent_practice',
         day_record->>'instructor_checks', day_record->>'assessment',
         day_record->>'teaching_tips', day_record->>'materials_equipment',
         day_record->>'evidence_check_for_understanding')
      returning id into guide_day_id;

      insert into public.course_guide_day_outcomes
        (school_id, course_id, guide_day_id, outcome_id)
      select course_record.school_id, course_record.id, guide_day_id, o.id
      from public.course_outcomes o
      where o.curriculum_id = target_curriculum_id
        and o.outcome_code in
          (select jsonb_array_elements_text(day_record->'outcome_codes'));

      if guide->>'course_code' = 'WLD 114' then
        insert into public.course_guide_day_resources
          (school_id, course_id, guide_day_id, sequence_number, resource_type,
           resource_title, resource_url, resource_notes, required,
           integration_mode, rights_basis, student_safe)
        values
          (course_record.school_id, course_record.id, guide_day_id, 1, 'website',
           'Torchmate Operator Hub — Instructor',
           '/resources/wld114/torchmate-operator-hub.html',
           'Instructor reference. Academy sign-in remains instructor-only; do not share licensed videos with student accounts.',
           false, 'url', 'school_owned', false);
      end if;

      for segment_record in select value from jsonb_array_elements(day_record->'segments') loop
        insert into public.course_guide_day_segments
          (school_id, course_id, guide_day_id, sequence_number, segment_type,
           segment_title, planned_minutes, instructor_actions, student_actions,
           start_minute, end_minute)
        values
          (course_record.school_id, course_record.id, guide_day_id,
           (segment_record->>'sequence_number')::integer,
           segment_record->>'segment_type', segment_record->>'segment_title',
           (segment_record->>'planned_minutes')::integer,
           segment_record->>'instructor_actions', segment_record->>'student_actions',
           (segment_record->>'start_minute')::integer,
           (segment_record->>'end_minute')::integer);
      end loop;
    end loop;
  end loop;
end
$ltg$;
""".replace("$ltg_json$DATA$ltg_json$", "$ltg_json$" + data + "$ltg_json$")

# PL/pgSQL identifiers are case insensitive; avoid variable/column ambiguity.
sql = sql.replace("guide_id uuid;", "target_guide_id uuid;")
sql = sql.replace("returning id into guide_id;", "returning id into target_guide_id;")
sql = sql.replace("where guide_id = guide_id;", "where course_guide_days.guide_id = target_guide_id;")
sql = sql.replace("(course_record.school_id, course_record.id, guide_id,", "(course_record.school_id, course_record.id, target_guide_id,")
OUTPUT.write_text(sql)
print(f"Wrote {len(guides)} draft guides to {OUTPUT.name}")
