import type { DemoProgram } from '../_lib/demo-types';

const WLD105_SAFETY = 'Use the print as a safety/control document: correct material, dimensions, notes and weld requirements before work begins. Reinforce stop-work and PPE expectations for paired shop work.';
const WLD105_PRINT_PROBLEMS = 'Students guess from the picture instead of reading the controlling view/note; confuse hidden/center/dimension lines; mix arrow-side/other-side; ignore units or tolerance.';
const WLD105_PRINT_TIPS = 'Keep a real part, enlarged print or simple weldment visible. Require “show me where the print says that” before accepting an answer.';
const WLD105_PRINT_CHECK = 'Ask the student to point to the exact drawing/symbol evidence supporting the answer. Record the concept demonstrated and the concept, if any, requiring targeted reteach.';
const WLD105_PRINT_RETRY = 'Reteach only the missed print/symbol concept, have the student explain one corrected example from the drawing, then recheck the same concept with a different item.';
const WLD105_QUALIFICATION = 'WLD-105 classroom/project evidence supports SENSE-aligned competency development but is not an AWS SENSE welder qualification by itself. Use “Qualified” only when a formal applicable AWS test is actually administered and documented.';
const WLD110_SAFETY = 'PPE, emergency/stop-work responsibility, ventilation, fire/hot-metal control, equipment inspection, correct setup and defect reporting before flame-on/energized work.';
const WLD110_CHECK = 'Student identifies the component/hazard, performs the inspection or dry setup in the correct sequence, states the defect response, and receives instructor clearance before operation.';
const WLD110_ASSESSMENT = 'Formative evidence: safe setup, procedure execution, visual inspection, parameter/result note and one identified improvement.';
const WLD110_PROBLEMS = 'Students treat inspection as a formality, miss damaged leads/hoses/fittings, confuse components, skip ventilation/housekeeping, or rush into operation before clearance.';
const WLD110_TIPS = 'Make students point, name and explain. A correct inspection sequence is more valuable than a fast lecture. Praise legitimate stop-work decisions.';
const WLD110_MATERIALS = 'PPE, OFC/SMAW stations, inspection checklists, defect tags, cylinder/component identification aids.';
const WLD110_SAFETY_GATE = 'Flame-on or energized practical work requires documented welding-safety clearance. If clearance is missing or suspended, the student remains in observation/dry-practice/remediation only. Correct unsafe conditions before coaching technique.';
const WLD110_PROCEDURE = 'Inspect equipment condition and work area first. Verify PPE, ventilation, connections, guards/safety devices, correct component identification and the approved setup/shutdown sequence before operation.';
const WLD110_ACCEPTANCE = 'Accept the setup only when PPE, work area, ventilation, equipment condition, connections and stop-work/defect response are correct before energizing or lighting.';
const WLD110_RETRY = 'Repeat only the failed inspection/setup step. Student identifies the hazard/defect, states the correct control, corrects the condition, then reruns the pre-use check before advancing.';
const WLD110_RECORD = 'Link the day’s inspection/setup checklist, parameter/procedure note, labeled practice result/photo if used, instructor verification and next-step note.';
const WLD110_QUALIFICATION = 'AWS alignment is instructional/competency support. “Qualified” is reserved for a formally configured and documented applicable AWS performance qualification, not ordinary practice or course completion.';

export const WELDING_DEMO_PROGRAM: DemoProgram = {
  id: 'welding',
  name: 'Welding Technology',
  schoolName: 'Demo Welding School',
  sectionLabel: 'WLD 105 / WLD 110 · Five-Day Live Demo',
  instructorName: 'Demo Instructor',
  description: 'An isolated five-day copy of the active WLD 105 and WLD 110 PVHS instructor guides. Curriculum content is a read-only snapshot; demo activity is temporary browser-session data only.',
  students: ['Jordan Lee', 'Maya Ortiz', 'Evan Brooks', 'Avery Patel', 'Noah Reed', 'Sofia Martinez'],
  courses: [
    {
      code: 'WLD 105',
      name: 'Safety, Blueprint Reading & Fabrication',
      roleLabel: '60-minute classroom / theory course',
      days: [
        {
          dayNumber: 1,
          title: 'Welcome to Welding + Welding Safety Video Day',
          objective: 'Set the tone for WLD-105, introduce welding and safety expectations, and complete the 20-minute Pre-Class Welding Math Assessment baseline.',
          formatLabel: '40 min WLD 105 + 20 min Pre-Class Welding Math Assessment',
          outcomes: [
            { id: 'w105-1-clo1', code: 'CLO 1', text: 'Apply prerequisite ANSI Z49.1 safety practices during all shop activities.' },
          ],
          rows: [
            { id: 'w105-d1-1', time: '0–8 min', instructor: 'Welcome, instructor/student introductions, prior experience, goals for the course. WLD-105/WLD-110 paired sequence, and AWS Safety Certificate verification. (verify on WTG and AWS learning)', kind: 'core' },
            { id: 'w105-d1-2', time: '8–12 min', instructor: 'What is welding? Where is it used? What does a welder actually do?', kind: 'core' },
            { id: 'w105-d1-3', time: '12–34 min', instructor: 'Play the selected Day 1 videos from the Welding Safety playlist. Students record hazards, controls, and PPE they notice.', kind: 'core' },
            { id: 'w105-d1-4', time: '34–38 min', instructor: 'Instructor-led recap: fire/explosion, burns, arc radiation, fumes, electrical hazards, PPE.', kind: 'core' },
            { id: 'w105-d1-5', time: '38–40 min', instructor: 'Exit check: name one hazard, one control/PPE item, and one safe action.', kind: 'assessment' },
            { id: 'w105-d1-6', time: '40–60 min', instructor: 'Launch the connected Pre-Class Welding Math Assessment. This is the baseline diagnostic used to identify support needs before the 45-Day Welding Mathematics sequence begins on Day 2. Do not coach answers during the assessment.', kind: 'assessment' },
          ],
          resources: [
            { id: 'w105-d1-r1', title: 'Day 1 Welding Safety Playlist', type: 'video', url: 'https://www.youtube.com/playlist?list=PLDcmN-SGrhdDEYBtmyguJnVvs4K97mPNR', notes: 'External linked resource', studentSafe: true },
            { id: 'w105-d1-r2', title: 'Pre-Class Welding Math Assessment', type: 'assessment', notes: 'Connected Live Classroom assessment · preclass_math', required: true, studentSafe: true, demoActivityKey: 'preclass_math' },
          ],
          support: {
            instructorPrep: 'BEFORE CLASS: Test the Day 1 Welding Safety Playlist from the LTG resource link, confirm sound/projector/internet, stage PPE examples, open the connected Pre-Class Welding Math Assessment, verify the student QR/link, and have the reporting view ready. Do not start the 20-minute assessment clock until students are successfully at the launch screen.',
            safetyFocus: 'Safety clearance, PPE, stop-work authority, emergency awareness, ventilation/hot-work controls, housekeeping and defect reporting.',
            instructorChecks: 'Require the student to explain the controlling requirement, show the evidence, and identify the next safe action.',
            assessment: 'End class with the connected 20-minute Pre-Class Welding Math Assessment. Diagnostic baseline only; use results to guide later support. The 45 instructional math lessons begin on Day 2.',
            commonProblems: 'Students describe the result without evidence, skip the planned checkpoint, or treat documentation as paperwork after the work instead of part of the work.',
            teachingTips: 'Make professional habits visible: follow the current work instruction, maintain records, inspect before/after the operation, and close the loop with a documented result.',
            materialsEquipment: 'Projector/display, internet access, PPE examples, whiteboard, Day 1 Welding Safety playlist; connected Pre-Class Welding Math Assessment; student devices as available.',
            correspondingApplication: 'Students should recognize the same hazards, PPE, emergency equipment, and safe behaviors whenever they enter the welding environment.',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders | Evidence: I / D. Exit response demonstrates hazard -> control/PPE -> safe action.',
            weeklyCoachingFocus: 'Set the culture before chasing content. Students should leave the first week curious, safe, and willing to ask before acting.',
            coachingFocus: 'Set the culture before chasing content. Students should leave the first week curious, safe, and willing to ask before acting.',
            ifStudentsStruggle: 'If attention drops during video segments, pause and ask one concrete question: “What could hurt you here, and what controls it?”',
            keepMomentum: 'End by naming what students did right: noticing hazards, asking questions, and taking PPE seriously. Safety culture starts with participation.',
            awsAlignment: 'AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders',
            awsKeyIndicators: 'M1: follow verbal/written instructions, maintain records, perform housekeeping. M2: PPE, safe work area, ventilation/hot-work controls, precautionary information, equipment inspection.',
            safetyGate: 'Verify the required welding-safety certificate/knowledge clearance before paired WLD-110 flame-on or energized work. A student not cleared remains in observation/dry-practice/remediation only.',
            evidenceType: 'I / D',
            qualificationGuardrail: WLD105_QUALIFICATION,
          },
        },
        {
          dayNumber: 2,
          title: 'Introduction to Welding: History, Industry & the Welder’s Role',
          objective: 'Students explain how welding developed, identify major welding process families and industries, describe the professional welder’s role, and connect the trade to the drawings used to communicate what must be built.',
          formatLabel: '40 min WLD 105 + 20 min Welding Math · Math Day 1',
          outcomes: [
            { id: 'w105-2-clo1', code: 'CLO 1', text: 'Apply prerequisite ANSI Z49.1 safety practices during all shop activities.' },
            { id: 'w105-2-clo5', code: 'CLO 5', text: 'Demonstrate proper use of mechanical shop tools for cutting, grinding, fitting, and finishing.' },
          ],
          rows: [
            { id: 'w105-d2-1', time: '0–5 min', instructor: 'Reconnect to Day 1: define welding as a manufacturing and fabrication process that joins materials. Frame the lesson around how the trade developed, where it is used, and what welders actually do.', kind: 'core' },
            { id: 'w105-d2-2', time: '5–15 min', instructor: 'Trace the progression from forge welding and blacksmithing to gas welding and cutting, resistance welding, arc welding, and the expansion of welding through shipbuilding, construction, pipelines, manufacturing, and modern automated or robotic systems.', kind: 'core' },
            { id: 'w105-d2-3', time: '15–25 min', instructor: 'Introduce the major process families students will encounter: SMAW, GMAW, FCAW, GTAW, and oxy-fuel cutting. Connect the processes to common industries and work environments.', kind: 'core' },
            { id: 'w105-d2-4', time: '25–34 min', instructor: 'Explain what professional welders do beyond striking an arc: read prints and WPSs, measure, fit, prepare joints, control heat, inspect work, document results, and work safely.', kind: 'core' },
            { id: 'w105-d2-5', time: '34–40 min', instructor: 'Show a simple welded part and its drawing. Ask: If I hand you steel, how do you know what to build? Use the answer to preview Day 3 blueprint reading.', kind: 'assessment' },
            { id: 'w105-d2-m1', time: '40–45 min', instructor: 'Welding Math Day 1 · Ask: “What can happen if a part is off by 1/16 inch?” Discuss 2-3 examples: poor fit, out-of-square work, wasted material, or misaligned holes/joints.', kind: 'math' },
            { id: 'w105-d2-m2', time: '45–50 min', instructor: 'Put on the board: 24 + 37 = 61; 3/4 = 0.75; 2 × (6 + 4) = 20. Teach: MEASURE → CALCULATE → CHECK → RECORD.', kind: 'math' },
            { id: 'w105-d2-m3', time: '50–55 min', instructor: 'Give each student one missed Pre-Class Math Assessment problem. Have them correct it and explain where that math is used in welding.', kind: 'math' },
            { id: 'w105-d2-m4', time: '55–60 min', instructor: 'Students choose one area to improve: fractions/tape measure, decimals/metric, or geometry/layout. Write one simple 45-day goal.', kind: 'math' },
          ],
          resources: [],
          support: {
            safetyFocus: 'Safety clearance, PPE, stop-work authority, emergency awareness, ventilation/hot-work controls, housekeeping and defect reporting.',
            materialsEquipment: 'PPE, equipment examples/photos, shop/facility safety checklist, AWS safety materials.',
            correspondingApplication: 'Students enter the paired WLD-110 period already knowing the day’s safety expectation and how to report a problem before equipment is used.',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders | Evidence: I / D. Student identifies common equipment/facility hazards and states the correct response.',
            weeklyCoachingFocus: 'Set the culture before chasing content. Students should leave the first week curious, safe, and willing to ask before acting.',
            coachingFocus: 'Set the culture before chasing content. Students should leave the first week curious, safe, and willing to ask before acting.',
            ifStudentsStruggle: 'Use one hazard at a time: What do you see? Why is it a problem? What would you do?',
            keepMomentum: 'Let students correct a staged safe/unsafe setup so the rule becomes visible.',
            instructorChecks: 'Require the student to explain the controlling requirement, show the evidence, and identify the next safe action.',
            assessment: 'Formative evidence: instructor observation, student explanation, approved plan/QC record or measured result tied to today’s objective.',
            commonProblems: 'Students describe the result without evidence, skip the planned checkpoint, or treat documentation as paperwork after the work instead of part of the work.',
            teachingTips: 'Make professional habits visible: follow the current work instruction, maintain records, inspect before/after the operation, and close the loop with a documented result.',
            awsAlignment: 'AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders',
            evidenceType: 'I / D',
            qualificationGuardrail: WLD105_QUALIFICATION,
          },
        },
        {
          dayNumber: 3,
          title: 'Introduction to Welding Drawings: From Print to Part',
          objective: 'Students explain why welders use drawings, identify the title block and basic drawing information, and begin connecting a 2D drawing to a physical part.',
          formatLabel: '40 min WLD 105 + 20 min Welding Math · Math Day 2',
          outcomes: [
            { id: 'w105-3-clo2', code: 'CLO 2', text: 'Interpret welding drawings, views, dimensions, tolerances, and weld symbols according to AWS A2.4 and EG2.0.' },
            { id: 'w105-3-clo3', code: 'CLO 3', text: 'Convert blueprint requirements into accurate physical layouts using shop tools.' },
          ],
          rows: [
            { id: 'w105-d3-1', time: '0–5 min', instructor: 'Quick safety retrieval from Days 1-2.', kind: 'core' },
            { id: 'w105-d3-2', time: '5–10 min', instructor: 'Why welders need blueprints: shared communication of material, dimensions, location, orientation, and requirements.', kind: 'core' },
            { id: 'w105-d3-3', time: '10–18 min', instructor: 'Drawing anatomy: title block, drawing area, notes, dimensions, material information, drawing identification.', kind: 'core' },
            { id: 'w105-d3-4', time: '18–27 min', instructor: 'Introduce object, hidden, center, dimension, and extension lines.', kind: 'core' },
            { id: 'w105-d3-5', time: '27–35 min', instructor: 'Introduce front, top, and side views using a simple physical object.', kind: 'core' },
            { id: 'w105-d3-6', time: '35–40 min', instructor: 'Print-to-part exercise and exit check.', kind: 'assessment' },
            { id: 'w105-d3-m1', time: '40–42 min', instructor: 'Welding Math Day 2 · Start: Ask: 28+17. Ask for an estimate before the exact answer.', kind: 'math' },
            { id: 'w105-d3-m2', time: '42–46 min', instructor: 'Show: Align place values in 1,248+375. Estimate 1,600; calculate 1,623; compare.', kind: 'math' },
            { id: 'w105-d3-m3', time: '46–52 min', instructor: 'Students practice: A rack has 14 ft, 22 ft, and 18 ft of angle. Students total the available length.', kind: 'math' },
            { id: 'w105-d3-m4', time: '52–58 min', instructor: 'Use it: Inventory shows 86 electrodes at start and 37 received. Write a complete inventory statement.', kind: 'math' },
            { id: 'w105-d3-m5', time: '58–60 min', instructor: 'Quick check: 128+76+9 = ?', kind: 'math' },
          ],
          resources: [],
          support: {
            safetyFocus: WLD105_SAFETY,
            materialsEquipment: 'Simple fabrication print, matching physical part/model, enlarged line-type examples, ruler/tape, whiteboard.',
            correspondingApplication: 'Students begin using drawings as the starting point for measuring, planning, and later project work.',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 3 Drawing and Welding Symbol Interpretation; Module 2 safety reinforcement | Evidence: I / D. Student identifies title block, one line type, one view, and one reason the drawing must be read before work begins.',
            coachingFocus: 'Make prints physical. Hold up a simple part, rotate it, and keep asking where that feature lives on the drawing.',
            ifStudentsStruggle: 'If views feel abstract, cover two views and work one view at a time before reconnecting them.',
            keepMomentum: 'Celebrate the first moment a student correctly links a line on paper to a feature on the part. That connection is the whole game.',
            instructorChecks: WLD105_PRINT_CHECK,
            commonProblems: WLD105_PRINT_PROBLEMS,
            teachingTips: WLD105_PRINT_TIPS,
            awsAlignment: 'AWS EG2.0 Level I: Module 3 Drawing and Welding Symbol Interpretation; Module 2 safety reinforcement',
            focusedRetry: WLD105_PRINT_RETRY,
            qualificationGuardrail: WLD105_QUALIFICATION,
          },
        },
        {
          dayNumber: 4,
          title: 'Views, Dimensions, Tolerances + Weld-Symbol Anatomy',
          objective: 'Students use multiple views, dimensions, tolerances, and basic welding-symbol anatomy to read a print before the 4-day blueprint review begins.',
          formatLabel: '40 min WLD 105 + 20 min Welding Math · Math Day 3',
          outcomes: [
            { id: 'w105-4-clo2', code: 'CLO 2', text: 'Interpret welding drawings, views, dimensions, tolerances, and weld symbols according to AWS A2.4 and EG2.0.' },
            { id: 'w105-4-clo3', code: 'CLO 3', text: 'Convert blueprint requirements into accurate physical layouts using shop tools.' },
            { id: 'w105-4-clo6', code: 'CLO 6', text: 'Evaluate fabricated components for squareness, dimensional accuracy, and weld quality.' },
          ],
          rows: [
            { id: 'w105-d4-1', time: '0–7 min', instructor: 'Orthographic review: front, top, and right-side views; visible vs. hidden information.', kind: 'core' },
            { id: 'w105-d4-2', time: '7–16 min', instructor: 'Dimensions: overall vs. feature dimensions, fractional/decimal dimensions, units, and measuring from the correct reference.', kind: 'core' },
            { id: 'w105-d4-3', time: '16–24 min', instructor: 'Tolerance concept: nominal size, acceptable range, and why “close enough” is not an inspection method.', kind: 'core' },
            { id: 'w105-d4-4', time: '24–32 min', instructor: 'Welding-symbol anatomy: reference line, arrow, tail, arrow side, and other side.', kind: 'core' },
            { id: 'w105-d4-5', time: '32–37 min', instructor: 'Connect symbol placement and basic dimensions to actual joints or photos.', kind: 'core' },
            { id: 'w105-d4-6', time: '37–40 min', instructor: 'Quick check: interpret one dimension/tolerance and label one basic welding symbol.', kind: 'assessment' },
            { id: 'w105-d4-m1', time: '40–42 min', instructor: 'Welding Math Day 3 · Start: Estimate 301−98, then calculate exactly.', kind: 'math' },
            { id: 'w105-d4-m2', time: '42–46 min', instructor: 'Show: Start with 96 in. Remove 18 in and 27 in: 96−18−27=51 in. Check by addition.', kind: 'math' },
            { id: 'w105-d4-m3', time: '46–52 min', instructor: 'Students practice: Find the remainder from 120 in after 34-in and 29-in cuts.', kind: 'math' },
            { id: 'w105-d4-m4', time: '52–58 min', instructor: 'Use it: Label a cut-list line: starting length, used length, remaining length, unit.', kind: 'math' },
            { id: 'w105-d4-m5', time: '58–60 min', instructor: 'Quick check: 240−86−19 = ?', kind: 'math' },
          ],
          resources: [],
          support: {
            safetyFocus: WLD105_SAFETY,
            materialsEquipment: 'Dimensioned prints, sample parts, tape/rule/caliper as available, large welding-symbol diagram, joint photos/samples.',
            correspondingApplication: 'WLD-110 reinforces the same measurement/reference-edge habits and joint/symbol language when students handle actual work.',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 3 Drawing and Welding Symbol Interpretation; Module 2 safety reinforcement | Evidence: I / D. Student reads a basic dimension/tolerance and identifies reference line, arrow, tail, and weld side.',
            coachingFocus: 'Keep dimensions and symbols tied to physical things. Abstract notation becomes useful when students can point to the feature it controls.',
            ifStudentsStruggle: 'Reduce the print to one dimension or one symbol at a time, then rebuild the full instruction.',
            keepMomentum: 'Require one plain-language explanation before adding complexity.',
            instructorChecks: WLD105_PRINT_CHECK,
            commonProblems: WLD105_PRINT_PROBLEMS,
            teachingTips: WLD105_PRINT_TIPS,
            awsAlignment: 'AWS EG2.0 Level I: Module 3 Drawing and Welding Symbol Interpretation; Module 2 safety reinforcement',
            focusedRetry: WLD105_PRINT_RETRY,
            qualificationGuardrail: WLD105_QUALIFICATION,
          },
        },
        {
          dayNumber: 5,
          title: 'Blueprint Reading for Welders - 4-Day Review Assessment: Day 1',
          objective: 'Review basic lines, views, notes, specifications, and dimensions; use multiple views to justify a print-reading decision.',
          formatLabel: '40 min WLD 105 + 20 min Welding Math · Math Day 4',
          outcomes: [
            { id: 'w105-5-clo2', code: 'CLO 2', text: 'Interpret welding drawings, views, dimensions, tolerances, and weld symbols according to AWS A2.4 and EG2.0.' },
            { id: 'w105-5-clo3', code: 'CLO 3', text: 'Convert blueprint requirements into accurate physical layouts using shop tools.' },
          ],
          rows: [
            { id: 'w105-d5-1', time: '0–7 min', instructor: 'Mini-review: front/top/right-side views, object/hidden/center/dimension/extension lines. INSTRUCTOR LEAD: Run this as retrieval, not another lecture. Ask students to point to the print, project, measurement, or prior evidence behind the answer. Correct the exact misconception, then recheck it with a second example before moving on.', kind: 'core' },
            { id: 'w105-d5-2', time: '7–17 min', instructor: 'Group task: V-Groove Test Block plus a dimensioned figure. Identify what each view tells you and point to four line types. INSTRUCTOR LEAD: Work the first example with the class, then have them take the next step while you circulate. If the same error appears twice, stop the room, correct that one decision clearly, and restart from the checkpoint.', kind: 'core' },
            { id: 'w105-d5-3', time: '17–33 min', instructor: 'Launch separate auto-graded assessment: Questions 1-20. INSTRUCTOR LEAD: State exactly what counts as evidence before students begin. Keep the check focused on today’s skill. Record the specific concept that needs reteach rather than a vague “needs help,” and protect test independence where the activity is an assessment.', kind: 'assessment' },
            { id: 'w105-d5-4', time: '33–40 min', instructor: 'Review missed concepts and require students to defend answers with print evidence. INSTRUCTOR LEAD: Run this as retrieval, not another lecture. Ask students to point to the print, project, measurement, or prior evidence behind the answer. Correct the exact misconception, then recheck it with a second example before moving on.', kind: 'core' },
            { id: 'w105-d5-m1', time: '40–42 min', instructor: 'Welding Math Day 4 · Start: Nine pieces at 6 in each—what operation is fastest and why?', kind: 'math' },
            { id: 'w105-d5-m2', time: '42–46 min', instructor: 'Show: Sixteen brackets at 7 in: 16×7=112 in=9 ft 4 in.', kind: 'math' },
            { id: 'w105-d5-m3', time: '46–52 min', instructor: 'Students practice: Find stock for 12 tabs at 5 in each, then convert to feet.', kind: 'math' },
            { id: 'w105-d5-m4', time: '52–58 min', instructor: 'Use it: Record quantity × length, total, and unit on a cut-list line.', kind: 'math' },
            { id: 'w105-d5-m5', time: '58–60 min', instructor: 'Quick check: 24 clips×3 in = ? in = ? ft', kind: 'math' },
          ],
          resources: [
            { id: 'w105-d5-r1', title: 'Launch Connected Test: Blueprint Reading — Day 1', type: 'assessment', notes: 'Planner-linked Blueprint Reading assessment · blueprint_day1 · 20 questions', studentSafe: true, demoActivityKey: 'blueprint_day1' },
          ],
          support: {
            instructorPrep: 'BEFORE CLASS: Read the full day plan and test every connected assessment/link that will be used. Stage an enlarged print or drawing, the matching symbol/reference material, and one physical/photo example. Decide the one misconception you most need to catch today and have a second example ready for the recheck.',
            safetyFocus: WLD105_SAFETY,
            openingReview: 'Mini-review: front/top/right-side views, object/hidden/center/dimension/extension lines. Run this as retrieval, not another lecture.',
            demonstration: 'MODEL TODAY’S DECISION: Use one actual print, project example, measurement, tool setup, QC record, or staged error from Blueprint Reading for Welders - 4-Day Review Assessment: Day 1. Think aloud: identify the requirement, show the decision, show the check, and show what evidence would allow the work to continue.',
            guidedPractice: 'Group task: V-Groove Test Block plus a dimensioned figure. Identify what each view tells you and point to four line types.',
            independentPractice: 'INSTRUCTOR-MONITORED APPLICATION: Give students a short application tied to today’s project or print. Circulate and question their reasoning. Do not accept “looks right”; require the print, measurement, procedure, rubric, or QC evidence that supports the decision.',
            instructorChecks: 'BEFORE MOVING ON: Ask at least one student to explain today’s key decision in plain language and point to the evidence that controls it. If the answer is wrong, correct only that concept, give a second example, and recheck before release to the next step.',
            assessment: 'Record the 20-question blueprint review result as diagnostic knowledge evidence. Use missed concepts for focused reteach; do not label the review alone as full AWS Module 3 certification evidence.',
            commonProblems: WLD105_PRINT_PROBLEMS,
            teachingTips: 'LEAD THE PRINT WORK. Keep the print/symbol visible. Ask “show me where the print says that” before accepting an answer. Praise evidence-based reasoning, then correct the exact reading error immediately.',
            materialsEquipment: 'Blueprint Reading for Welders or assigned print packet; V-Groove Test Block drawing; separate auto-graded assessment.',
            correspondingApplication: 'Students connect multiple views and dimensions to decisions they will later make when laying out and checking parts.',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 3 Drawing and Welding Symbol Interpretation; Module 2 safety reinforcement | Evidence: K / I / D. 20-question review record plus instructor observation of print-based justification. DAY-SPECIFIC PROOF: Review missed concepts and require students to defend answers with print evidence.',
            weeklyCoachingFocus: 'Make print reading active and physical. Students should increasingly point to evidence before speaking.',
            coachingFocus: 'Build confidence through evidence: students do not have to guess a print. Teach them to find the controlling line, view, note, dimension, tolerance, or symbol and defend the answer.',
            ifStudentsStruggle: 'Reduce the task to one source question: Which view, line, note, dimension, tolerance, or symbol controls this answer? Cover unrelated information, solve that one decision, then add the rest back.',
            keepMomentum: 'When students correctly defend an answer with print evidence, say so explicitly and move them to a slightly more complex example rather than repeating the same easy item.',
            awsAlignment: 'AWS EG2.0 Level I: Module 3 Drawing and Welding Symbol Interpretation; Module 2 safety reinforcement',
            evidenceType: 'K / I / D',
            focusedRetry: WLD105_PRINT_RETRY,
            recordLinkExpectation: 'Link the assessment/review result, corrected item(s), instructor verification and any targeted-reteach note to the day.',
            qualificationGuardrail: WLD105_QUALIFICATION,
          },
        },
      ],
    },
    {
      code: 'WLD 110',
      name: 'OFC, Basic SMAW & Fabrication',
      roleLabel: '120-minute lab / shop course',
      days: [
        {
          dayNumber: 1,
          title: 'Course Orientation + Entry Requirements',
          objective: 'Explain course expectations and verify entry and safety requirements before shop work begins.',
          formatLabel: '120 min WLD 110 · 0–25 Toolbox Talk/Demo · 25–75 Primary Practice · 75–105 Secondary Application · 105–120 Shutdown',
          outcomes: [
            { id: 'w110-1-clo1', code: 'CLO 1', text: 'Complete OFC and SMAW safety inspections and identify equipment defects using AWS-aligned procedures.' },
            { id: 'w110-1-clo2', code: 'CLO 2', text: 'Explain and apply OFC and SMAW process fundamentals, including gas properties, flame characteristics, polarity, and electrode selection.' },
          ],
          rows: [
            { id: 'w110-d1-1', time: '0–25 min', instructor: 'Evacuation Expectations: explain stop work, exit, rally point, accountability, and emergency-door expectations. Stop-Work Culture: RAISED FIST = STOP. Anyone seeing an immediate safety concern raises a fist and identifies the hazard; work stops until resolved and instructor-cleared. Stage and identify SMAW PPE/tools: welding helmet, leather jacket, safety glasses, hearing protection, SMAW gloves, slip-joint pliers, chipping hammer, wire brush, grinder, and wire wheel. INSTRUCTOR LEAD: Point, name, explain, then have students point back to emergency equipment or safety controls.', kind: 'core' },
            { id: 'w110-d1-2', time: '25–75 min', instructor: 'HELMET SETUP, GRINDER SETUP, AND E6010 ARC-START DEMONSTRATION. Helmet: fit headgear, practice raising/lowering, review shade/sensitivity where applicable, verify operation, keep safety glasses on. Grinder: UNPLUGGED during setup, guard adjustment, accessory install/removal, and inspection. Demonstrate controls, guard position, wheel/wire-wheel inspection, approved accessory installation, two-handed operation, body position, spark direction, and required PPE. E6010 arc start: identify electrode, holder and work connection; demonstrate body/hand position, helmet movement, proper arc strike, sticking, excessive arc length, and transition to controlled arc length. First goal is ARC CONTROL, not a finished weld.', kind: 'core' },
            { id: 'w110-d1-3', time: '75–105 min', instructor: 'OFC SAFETY, SETUP, LIGHTING, CUTTING, SHUTDOWN, AND DISASSEMBLY DEMONSTRATION. Review PPE first. Identify oxygen/fuel cylinders, regulators/gauges, hoses, check valves/flashback protection, torch body, cutting attachment, tip and striker. Demonstrate: Inspect -> Assemble -> Check Connections -> Leak Test -> Verify -> Light with approved striker -> Adjust flame -> Establish cutting flame -> Demonstrate torch position/preheat/cutting oxygen -> Shut Down -> Close Cylinders -> Relieve Pressure -> Back Out Regulator Screws -> Disassemble/Store. Stop at leak-test and shutdown checkpoints and ask what would make the class stop.', kind: 'core' },
            { id: 'w110-d1-4', time: '105–120 min', instructor: 'SAFE SHUTDOWN / CLOSEOUT. Verify hot-metal control, welding/OFC shutdown as applicable, grinder/tool accountability, booth cleanup, labeled work, and parameter/progress notes. No uncontrolled hot material or loose equipment remains. INSTRUCTOR LEAD: Walk the room and end by naming the next shop-ready target for Day 2.', kind: 'core' },
          ],
          resources: [
            { id: 'w110-d1-r1', title: 'WLD 110 2026-2027 Course Requirements and Grading Overview', type: 'student_resource', notes: 'Uses the existing six locked LTG outcomes; four grading categories are 25% each.', required: true, studentSafe: true },
          ],
          support: {
            instructorPrep: 'BEFORE CLASS: Walk the emergency-tour route and confirm exits, extinguishers, eyewash, first aid, AED, rally point, ventilation and stop-work expectations. Stage the PPE/tool table, helmets, unplugged grinders/accessories, E6010 demonstration station, and OFC equipment before students enter. Confirm all live-demo equipment is serviceable and the shop is ready for controlled demonstrations.',
            safetyFocus: WLD110_SAFETY,
            instructorChecks: WLD110_CHECK,
            assessment: WLD110_ASSESSMENT,
            commonProblems: WLD110_PROBLEMS,
            teachingTips: WLD110_TIPS,
            materialsEquipment: WLD110_MATERIALS,
            correspondingApplication: 'WLD-105 Coordination Cue: Welcome to Welding + Welding Safety Video Day',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders; introductory Module 4 SMAW and Module 8 Thermal Cutting controls | Evidence: I / D. Student completes the inspection/identification routine and correctly explains the main hazard or defect response.',
            weeklyCoachingFocus: 'Establish a calm, professional shop culture: inspect first, ask when unsure, stop work when unsafe, and treat setup/shutdown discipline as part of welding skill.',
            coachingFocus: 'Lead the room visibly. Name the safety reason before each demonstration, show the correct sequence, and tell students exactly what they should watch for. Praise correct stop-work decisions and careful setup.',
            ifStudentsStruggle: 'Slow the sequence down. Ask for one location/tool, one hazard, and one safe response at a time. Re-demo the exact step, then have the student teach it back before moving on.',
            keepMomentum: 'Give students visible wins: correctly locating emergency equipment, fitting PPE, completing grinder setup, or making the first controlled arc-start motion. Keep the day moving without rushing the safety sequence.',
            awsAlignment: 'AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders; introductory Module 4 SMAW and Module 8 Thermal Cutting controls',
            safetyGate: WLD110_SAFETY_GATE,
            procedureVariableFocus: WLD110_PROCEDURE,
            inspectionAcceptanceFocus: WLD110_ACCEPTANCE,
            focusedRetry: WLD110_RETRY,
            recordLinkExpectation: WLD110_RECORD,
            qualificationGuardrail: WLD110_QUALIFICATION,
          },
        },
        {
          dayNumber: 2,
          title: 'PPE + Hot-Work Hazard Review',
          objective: 'Inspect PPE and identify hot-work hazards before entering an active work area.',
          formatLabel: '120 min WLD 110 · 0–25 Toolbox Talk/Demo · 25–75 Primary Practice · 75–105 Secondary Application · 105–120 Shutdown',
          outcomes: [
            { id: 'w110-2-clo1', code: 'CLO 1', text: 'Complete OFC and SMAW safety inspections and identify equipment defects using AWS-aligned procedures.' },
          ],
          rows: [
            { id: 'w110-d2-1', time: '0–25 min', instructor: 'STUDENT SHOP-READY INSPECTION + BOOTH SETUP. Verify safety glasses, welding clothing, work boots, jewelry/watches, long hair, and loose/unsafe items. Once cleared, students select the assigned/available booth, bring the assigned quench bucket, inspect the booth/work area, and gather safety glasses, helmet, jacket, stick gloves, chipping hammer, wire brush, grinder, and slip-joint pliers. Grinder is plugged in only after setup/accessory checks. Use the phrase: SET YOURSELF UP FOR SUCCESS.', kind: 'core' },
            { id: 'w110-d2-2', time: '25–75 min', instructor: 'SHOP SAFETY, VENTILATION, AND WELDER SETUP. Review ventilation, welding screens, nearby-personnel protection, fire prevention, hot-metal control, housekeeping, emergency stop/notification procedures, and the 3-Weld Quench Rule. Show extractor ON/OFF controls and state welding does not begin without required ventilation. Identify welding-machine controls/components and demonstrate pre-use inspection, connections, selection of settings, safe start, operation and shutdown.', kind: 'core' },
            { id: 'w110-d2-3', time: '75–105 min', instructor: 'FIRST E6010 ARC-STARTING PRACTICE. Issue each student 4 x 1/8 in E6010 electrodes and one 3/8 in x 3 in x 4 in steel practice plate. Set flat position, demonstrate secure clamping, and check each setup. Students attempt strike/restart, maintain the arc long enough to begin a bead, and make a basic bead. Goal: comfort with holder, arc initiation, and basic arc control; bead appearance is secondary. Give one correction at a time: setup/body position -> helmet coordination -> strike -> arc length.', kind: 'core' },
            { id: 'w110-d2-4', time: '105–120 min', instructor: 'SAFE SHUTDOWN / CLOSEOUT. Shut machines down, control hot metal, quench only according to the program rule, return tools, clean booths, label work, and complete the progress/parameter log. NO METAL LEFT IN BOOTHS. Verify each booth before release.', kind: 'core' },
          ],
          resources: [
            { id: 'w110-d2-r1', title: 'ANSI Z49.1 Safety Practices Reference', type: 'aws_reference', notes: 'Use the program-approved safety reference and local shop procedures.', required: true, studentSafe: true },
          ],
          support: {
            instructorPrep: 'BEFORE CLASS: Stage the shop-ready inspection area, quench buckets, booth tools, E6010 practice plates/electrodes, ventilation controls, and one welding machine for identification. Confirm grinders are staged safely and remain unplugged until setup/accessory checks are complete. Prepare one intentionally flawed booth/setup for students to diagnose.',
            safetyFocus: WLD110_SAFETY,
            demonstration: 'TOOLBOX TALK / DEMO - MAIN SHOP: Inspect welding PPE for condition, fit, correct lens/shade use, clothing coverage, hearing protection, and footwear. Connect the demonstration directly to the procedure students will practice today: PPE + Hot-Work Hazard Review.',
            guidedPractice: 'Review ventilation, screens, fire prevention, hot-metal control, housekeeping, and emergency stop/notification procedures.',
            independentPractice: 'Run a hazard-spotting exercise at OFC and SMAW workstations; correct each condition before work begins.',
            instructorChecks: WLD110_CHECK,
            assessment: WLD110_ASSESSMENT,
            commonProblems: WLD110_PROBLEMS,
            teachingTips: WLD110_TIPS,
            materialsEquipment: WLD110_MATERIALS,
            correspondingApplication: 'Welding Safety Applied to Oxy-Fuel Equipment',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders; introductory Module 4 SMAW and Module 8 Thermal Cutting controls | Evidence: I / D. Student completes the inspection/identification routine and correctly explains the main hazard or defect response.',
            weeklyCoachingFocus: 'Build repeatable booth and machine routines. Students should leave knowing how to prepare themselves, prepare the booth, start safely, and close out correctly.',
            coachingFocus: 'Coach setup before arc quality. One correct correction followed by immediate retry is more useful than five comments at once.',
            ifStudentsStruggle: 'Fix the setup first: PPE, booth, ventilation, machine connections, body/helmet position, then arc start. Do not chase bead appearance while the foundation is wrong.',
            keepMomentum: 'Celebrate the first complete shop-ready setup and first controlled arc start. Students who are ready can repeat purposeful arc starts; students still building setup skill stay on the exact missing checkpoint.',
            safetyGate: WLD110_SAFETY_GATE,
            procedureVariableFocus: WLD110_PROCEDURE,
            inspectionAcceptanceFocus: WLD110_ACCEPTANCE,
            focusedRetry: WLD110_RETRY,
            recordLinkExpectation: WLD110_RECORD,
            qualificationGuardrail: WLD110_QUALIFICATION,
          },
        },
        {
          dayNumber: 3,
          title: 'OFC System Identification + Cylinder Handling',
          objective: 'Identify the major OFC components and handle compressed-gas cylinders correctly.',
          formatLabel: '120 min WLD 110 · 0–25 Toolbox Talk/Demo · 25–75 Primary Practice · 75–105 Secondary Application · 105–120 Shutdown',
          outcomes: [
            { id: 'w110-3-clo1', code: 'CLO 1', text: 'Complete OFC and SMAW safety inspections and identify equipment defects using AWS-aligned procedures.' },
            { id: 'w110-3-clo2', code: 'CLO 2', text: 'Explain and apply OFC and SMAW process fundamentals, including gas properties, flame characteristics, polarity, and electrode selection.' },
          ],
          rows: [
            { id: 'w110-d3-1', time: '0–25 min', instructor: 'OFC SYSTEM IDENTIFICATION + CYLINDER HANDLING. Identify oxygen and approved fuel-gas cylinders by LABEL, not color alone. Review securing cylinders, valve-protection caps, safe transport, separation/storage expectations, and protection from damage. Identify regulators, gauges, oxygen/fuel hoses, check valves/flashback protection, torch body, cutting attachment and tips. Require students to name each component and one safety purpose/control.', kind: 'core' },
            { id: 'w110-d3-2', time: '25–75 min', instructor: 'OFC SETUP, LEAK TEST, LIGHTING, SHUTDOWN, AND DISASSEMBLY PRACTICE. Demonstrate: Inspect -> Connect -> Set Regulators as instructed -> Check Connections -> Leak Test -> Verify -> Light/Adjust -> Shut Down -> Relieve Pressure -> Disassemble. Coach repeated cycles. Each student identifies components, performs required checks, and receives instructor verification before lighting. If no leaks are found, allow brief controlled light/operation, followed by correct shutdown and disassembly.', kind: 'core' },
            { id: 'w110-d3-3', time: '75–105 min', instructor: 'FIRST OFC CUTTING PRACTICE. Only students who have completed TWO successful setup/leak-test/light/shutdown/disassembly cycles move to cutting. Verify assembly, leak test, flame adjustment and shutdown sequence. Coach workpiece preparation, safe body/torch position, correct cutting flame, edge preheat, cutting oxygen use, torch angle/tip distance/travel speed, and hot-metal handling. First goal is a safe completed cut with controlled torch movement, not a perfect edge. Call students CLEARED FOR FIRST CUT, not qualified.', kind: 'core' },
            { id: 'w110-d3-4', time: '105–120 min', instructor: 'SAFE SHUTDOWN / CLOSEOUT. Verify correct OFC shutdown, cylinder valves closed as required, pressure relieved, regulator screws backed out, equipment stored, hot metal controlled, work area clean, tools accounted for, and progress notes completed. Ask one student to verbally walk the shutdown sequence while you visually verify the station.', kind: 'core' },
          ],
          resources: [
            { id: 'w110-d3-r1', title: 'AWS Oxy-Fuel Cutting (OFC) Instructional Packet', type: 'aws_reference', notes: 'Program-issued packet used for OFC theory, setup, cutting, and review.', required: true, studentSafe: true },
          ],
          support: {
            instructorPrep: 'BEFORE CLASS: Stage an OFC system for component identification plus student setup stations. Confirm cylinders are secured, caps/valves protected, hoses/regulators/torch components are serviceable, leak-test materials are ready, and first-cut coupons are prepared. Know the exact clearance gate: two successful setup/leak-test/light/shutdown/disassembly cycles before cutting.',
            safetyFocus: WLD110_SAFETY,
            demonstration: 'TOOLBOX TALK / DEMO - MAIN SHOP: Identify oxygen and approved fuel-gas cylinders by label; review securing, caps, transport, separation, and valve-protection rules. Connect the demonstration directly to the procedure students will practice today: OFC System Identification + Cylinder Handling.',
            guidedPractice: 'Identify regulators, gauges, hoses, check valves/flashback protection, torch body, cutting attachment, and tips.',
            independentPractice: 'Complete a dry equipment-identification check; cylinders remain closed unless the instructor authorizes setup.',
            instructorChecks: WLD110_CHECK,
            assessment: WLD110_ASSESSMENT,
            commonProblems: WLD110_PROBLEMS,
            teachingTips: WLD110_TIPS,
            materialsEquipment: WLD110_MATERIALS,
            correspondingApplication: 'Introduction to Welding Drawings: From Print to Part',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders; introductory Module 4 SMAW and Module 8 Thermal Cutting controls | Evidence: I / D. Student completes the inspection/identification routine and correctly explains the main hazard or defect response.',
            weeklyCoachingFocus: 'Make the OFC sequence consistent every time. Students earn cutting time through safe setup control, not speed.',
            coachingFocus: 'Require students to name the OFC component and the safety purpose before touching it. Progression is Inspect -> Set Up -> Leak Test -> Verify -> Light -> Shut Down -> Disassemble -> Repeat.',
            ifStudentsStruggle: 'Return to the OFC checklist and repeat only the missed step. Keep cylinders closed until the dry sequence is correct; do not advance to cutting because the clock is winning.',
            keepMomentum: 'Record each successful OFC cycle. Students who complete two correct cycles advance to first cuts; others keep practicing the same sequence until it is reliable.',
            safetyGate: WLD110_SAFETY_GATE,
            procedureVariableFocus: WLD110_PROCEDURE,
            inspectionAcceptanceFocus: WLD110_ACCEPTANCE,
            focusedRetry: WLD110_RETRY,
            recordLinkExpectation: WLD110_RECORD,
            qualificationGuardrail: WLD110_QUALIFICATION,
          },
        },
        {
          dayNumber: 4,
          title: 'OFC External Inspection + Defect Reporting',
          objective: 'Complete an external OFC inspection and correctly tag and report visible defects.',
          formatLabel: '120 min WLD 110 · 0–25 Toolbox Talk/Demo · 25–75 Primary Practice · 75–105 Secondary Application · 105–120 Shutdown',
          outcomes: [
            { id: 'w110-4-clo1', code: 'CLO 1', text: 'Complete OFC and SMAW safety inspections and identify equipment defects using AWS-aligned procedures.' },
          ],
          rows: [
            { id: 'w110-d4-1', time: '0–25 min', instructor: 'OFC EXTERNAL INSPECTION + COMPLETE CUTTING DEMONSTRATION. Inspect cylinder connections, regulators, gauges, oxygen/fuel hoses, torch body, cutting attachment, cutting tip/tip seats, check valves/flashback protection and safety devices. Look for visible damage, loose/damaged fittings, contamination, damaged hose sections, defective gauges/regulators, and damaged/dirty tip seats. Demonstrate: Inspect -> Assemble -> Set Regulators -> Leak Test -> Verify -> Light/Adjust -> Cut -> Shut Down -> Relieve Pressure -> Disassemble. Show at least one staged defect and ask: Use, clean/replace consumable, or tag out? Why?', kind: 'core' },
            { id: 'w110-d4-2', time: '25–75 min', instructor: 'OFC STRAIGHT-LINE CUTTING PRACTICE. Release only students who successfully complete the required inspection/setup/testing sequence. Coach secure workpiece position, body/torch position, cutting flame, preheat, cutting oxygen, straight-line travel, torch height/angle/travel speed, cut inspection, and hot-metal control. Students not yet reliable in setup continue setup practice until cleared. Correct one variable at a time and compare the next cut to the previous one.', kind: 'core' },
            { id: 'w110-d4-3', time: '75–105 min', instructor: 'DEFECT REPORTING + APPROVED EQUIPMENT CARE. Practice three decisions: (1) serviceable and safe to use, (2) approved external cleaning or consumable replacement, or (3) TAG OUT and report for authorized repair. Student service is limited to approved external cleaning/consumable replacement. Have students tag a staged defect, state it clearly, and identify the reporting path. Recheck with a second example before release.', kind: 'core' },
            { id: 'w110-d4-4', time: '105–120 min', instructor: 'SAFE SHUTDOWN / CLOSEOUT. Complete OFC shutdown/disassembly, control hot metal, clean the cutting area, return tools/components, label work, and complete the parameter/progress log. Close by asking: What defect today would stop you from lighting the torch?', kind: 'core' },
          ],
          resources: [],
          support: {
            instructorPrep: 'BEFORE CLASS: Stage a complete OFC system, inspection checklist, defect tags, examples of acceptable vs damaged/contaminated components, cutting coupons, and approved cleaning/consumable-replacement items. Identify which defects require immediate tag-out and authorized repair.',
            safetyFocus: WLD110_SAFETY,
            demonstration: 'TOOLBOX TALK / DEMO - MAIN SHOP: Inspect cylinder connections, regulators, gauges, hoses, torch, tip seats, and required safety devices for visible damage or contamination. Connect the demonstration directly to the procedure students will practice today: OFC External Inspection + Defect Reporting.',
            guidedPractice: 'Practice tagging equipment out of service and reporting the defect using the program inspection checklist.',
            independentPractice: 'Limit student service to approved external cleaning or consumable replacement; damaged components go to authorized repair.',
            instructorChecks: WLD110_CHECK,
            assessment: WLD110_ASSESSMENT,
            commonProblems: WLD110_PROBLEMS,
            teachingTips: WLD110_TIPS,
            materialsEquipment: WLD110_MATERIALS,
            correspondingApplication: 'Orthographic Views & Line Types',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 1 Occupational Orientation + Module 2 Safety and Health of Welders; introductory Module 4 SMAW and Module 8 Thermal Cutting controls | Evidence: I / D. Student completes the inspection/identification routine and correctly explains the main hazard or defect response.',
            weeklyCoachingFocus: 'Normalize defect reporting and tag-out as professional behavior. A student who stops unsafe equipment is doing the job correctly.',
            coachingFocus: 'Teach inspection as a decision: serviceable, approved external care, or tag out. Do not let minor damage become normal.',
            ifStudentsStruggle: 'Use one staged defect at a time. Ask: What do you see? Is it safe to use? What is the allowed response? Require the student to point to the component and state the decision.',
            keepMomentum: 'Use quick inspection challenges and immediate rechecks. Strong students can diagnose a second staged defect or explain why an apparently small defect requires tag-out.',
            safetyGate: WLD110_SAFETY_GATE,
            procedureVariableFocus: WLD110_PROCEDURE,
            inspectionAcceptanceFocus: WLD110_ACCEPTANCE,
            focusedRetry: WLD110_RETRY,
            recordLinkExpectation: WLD110_RECORD,
            qualificationGuardrail: WLD110_QUALIFICATION,
          },
        },
        {
          dayNumber: 5,
          title: 'SMAW Equipment Inspection + Safety Checkpoint',
          objective: 'Inspect SMAW equipment and use a repeatable pre-use safety routine.',
          formatLabel: '120 min WLD 110 · 0–25 Toolbox Talk/Demo · 25–75 Primary Practice · 75–105 Secondary Application · 105–120 Shutdown',
          outcomes: [
            { id: 'w110-5-clo1', code: 'CLO 1', text: 'Complete OFC and SMAW safety inspections and identify equipment defects using AWS-aligned procedures.' },
          ],
          rows: [
            { id: 'w110-d5-1', time: '0–25 min', instructor: 'TOOLBOX TALK / DEMO - MAIN SHOP: Inspect the power source, electrode holder, work clamp, leads, connectors, booth, and ventilation before energizing. Connect the demonstration directly to the procedure students will practice today: SMAW Equipment Inspection + Safety Checkpoint. INSTRUCTOR LEAD: Open by naming today’s performance target and the safety reason it matters. Stage the exact tools/materials, demonstrate once while narrating setup, body/holder position, variables and visual evidence, pause at the critical checkpoint, and ask what condition would make the student stop.', kind: 'core' },
            { id: 'w110-d5-2', time: '25–75 min', instructor: 'Identify damaged insulation, loose connections, wet conditions, poor lead routing, and trip hazards; tag out defects. INSTRUCTOR LEAD: Set one visible success target. Circulate continuously. Give one actionable correction at a time, then require an immediate retry. If the same error appears across the class, stop for a brief re-demo and restart from that checkpoint. Praise correct setup/procedure control as strongly as finished appearance.', kind: 'core' },
            { id: 'w110-d5-3', time: '75–105 min', instructor: 'Complete a short OFC/SMAW safety checkpoint and correct missed items as a group. INSTRUCTOR LEAD: Release only students who have met the setup/safety gate. Require purposeful repetitions, not volume. Have each student compare the result to today’s acceptance focus, label/save the best evidence, and record one parameter/result/next adjustment. Strong students earn a harder quality target, not permission to rush.', kind: 'core' },
            { id: 'w110-d5-4', time: '105–120 min', instructor: 'Safe shutdown, hot-metal control, cleanup/tool accountability, label work, and complete the parameter/progress log. INSTRUCTOR LEAD: Begin closeout with enough time. Verify power/flame/gas shutdown as applicable, hot-metal control, booth cleanup, tools, leads/hoses, no scrap left in booths, labeled work and the progress/parameter log. End with one clear next target.', kind: 'core' },
          ],
          resources: [
            { id: 'w110-d5-r1', title: 'AWS Shielded Metal Arc Welding (SMAW) Instructional Packet', type: 'aws_reference', notes: 'Program-issued packet used for SMAW theory, electrodes, positions, and review.', required: true, studentSafe: true },
          ],
          support: {
            instructorPrep: 'BEFORE CLASS: Read the complete day plan and stage the exact OFC/SMAW equipment, PPE, coupons/electrodes, inspection checklist and demonstration materials required today. Confirm ventilation, guards/safety devices, leads/hoses/connections and hot-work controls. Prepare one correct example and one realistic error. Know the safety gate and the exact evidence students must produce before moving on.',
            safetyFocus: WLD110_SAFETY,
            demonstration: 'TOOLBOX TALK / DEMO - MAIN SHOP: Inspect the power source, electrode holder, work clamp, leads, connectors, booth, and ventilation before energizing. Connect the demonstration directly to the procedure students will practice today: SMAW Equipment Inspection + Safety Checkpoint.',
            guidedPractice: 'Identify damaged insulation, loose connections, wet conditions, poor lead routing, and trip hazards; tag out defects.',
            independentPractice: 'Complete a short OFC/SMAW safety checkpoint and correct missed items as a group.',
            instructorChecks: WLD110_CHECK,
            assessment: 'Safety/equipment inspection checkpoint. Any safety-critical miss is corrected and rechecked before energized practice continues.',
            commonProblems: WLD110_PROBLEMS,
            teachingTips: WLD110_TIPS,
            materialsEquipment: WLD110_MATERIALS,
            correspondingApplication: 'Blueprint Reading for Welders - 4-Day Review Assessment: Day 1',
            evidenceCheck: 'AWS SENSE alignment: AWS EG2.0 Level I: Module 2 Safety + Module 4 SMAW KI 1 equipment/accessory safety inspection | Evidence: I / V / D. Student completes the inspection/identification routine and correctly explains the main hazard or defect response.',
            weeklyCoachingFocus: 'Build repeatable safe routines before speed: inspect, identify, set up, verify, operate, inspect the result, shut down and record.',
            coachingFocus: 'Lead with the safety/setup sequence, then coach technique. Praise correct inspection and stop-work decisions as real welding performance.',
            ifStudentsStruggle: 'Return to the checklist and make the system safe. Isolate the missed component/setup step, correct it, then rerun only that sequence before advancing.',
            keepMomentum: 'Use quick teach-backs and visible clearance checkpoints. Students who are secure earn the next controlled step; students still building the routine stay on the exact missing skill.',
            awsAlignment: 'AWS EG2.0 Level I: Module 2 Safety + Module 4 SMAW KI 1 equipment/accessory safety inspection',
            safetyGate: WLD110_SAFETY_GATE,
            procedureVariableFocus: WLD110_PROCEDURE,
            inspectionAcceptanceFocus: WLD110_ACCEPTANCE,
            focusedRetry: WLD110_RETRY,
            recordLinkExpectation: WLD110_RECORD,
            qualificationGuardrail: WLD110_QUALIFICATION,
          },
        },
      ],
    },
  ],
};
