-- Ensure the two public demo assessments exist in isolated/staging environments.
-- Existing production assessment content is left untouched.

insert into public.assessment_modules(slug,title,description,category,estimated_minutes,sort_order,version,active)
values
('preclass_math','Pre-Class Welding Math Assessment','Measures fractions, decimals, shop arithmetic, tape measurement, layout, area, and conversions.','Welding Mathematics',20,10,1,true),
('blueprint_day1','Blueprint Reading — Day 1 • Basic lines, views, notes, and dimensions','Unit 1, pp. 1-7 • Unit 3, pp. 17-21 • Unit 4, pp. 22-37 | Line types, visible vs. hidden information, notes/specifications, and dimension reading.','Blueprint Reading',20,20,143,true)
on conflict(slug) do nothing;

insert into public.assessment_questions(assessment_slug,question_key,question_number,question_type,question_text,domain,options,correct_answer,accepted_answers,explanation) values
('preclass_math','q1',1,'mc','Which of the following is equal to 1/2 inch in decimal form?','Fractions & Decimals','{"A":"0.25","B":"0.50","C":"0.75","D":"0.33"}','B',null,'1 ÷ 2 = 0.50.'),
('preclass_math','q2',2,'mc','What is 7/8 inch as a decimal?','Fractions & Decimals','{"A":"0.875","B":"0.625","C":"0.0875","D":"0.857"}','A',null,'7 ÷ 8 = 0.875.'),
('preclass_math','q3',3,'mc','Which fraction is the same as 0.375?','Fractions & Decimals','{"A":"3/8","B":"5/8","C":"7/8","D":"1/4"}','A',null,'3 ÷ 8 = 0.375.'),
('preclass_math','q4',4,'mc','Convert 0.625 inches to a fraction.','Fractions & Decimals','{"A":"5/8","B":"3/4","C":"7/8","D":"1/2"}','A',null,'0.625 = 5/8.'),
('preclass_math','q5',5,'mc','Which of the following is the smallest?','Fractions & Decimals','{"A":"1/8","B":"0.150","C":"3/16","D":"0.25"}','A',null,'1/8 = 0.125.'),
('preclass_math','q6',6,'mc','You have a piece of metal 12 inches long. You cut off 3 5/8 inches. How much remains?','Shop Arithmetic','{"A":"8 3/8 in","B":"9 1/2 in","C":"8 1/4 in","D":"8 5/8 in"}','A',null,'12 - 3 5/8 = 8 3/8 inches.'),
('preclass_math','q7',7,'mc','What is 3 3/4 in + 2 1/8 in?','Shop Arithmetic','{"A":"5 5/8 in","B":"5 7/8 in","C":"6 in","D":"6 1/4 in"}','B',null,'3 6/8 + 2 1/8 = 5 7/8 inches.'),
('preclass_math','q8',8,'mc','A weld joint needs a 1/4-inch gap, but the current gap is 3/8 inch. By how much must the gap be reduced?','Shop Arithmetic','{"A":"1/8 in","B":"1/4 in","C":"3/8 in","D":"1/16 in"}','A',null,'3/8 - 1/4 = 1/8 inch.'),
('preclass_math','q9',9,'mc','Multiply: 5 1/2 in × 2 = ?','Shop Arithmetic','{"A":"10 in","B":"11 in","C":"11 1/2 in","D":"12 in"}','B',null,'5.5 × 2 = 11 inches.'),
('preclass_math','q10',10,'mc','A 48-inch plate is cut into four equal parts. What is the length of each part?','Shop Arithmetic','{"A":"12 in","B":"10 in","C":"11.5 in","D":"12.5 in"}','A',null,'48 ÷ 4 = 12 inches.'),
('preclass_math','q11',11,'mc','On a tape measure divided into 1/16-inch increments, what measurement is the fourth small line after 3 inches?','Tape & Measurement','{"A":"3 1/4 in","B":"3 3/8 in","C":"3 5/16 in","D":"3 7/16 in"}','A',null,'Four 1/16-inch increments equal 1/4 inch.'),
('preclass_math','q12',12,'mc','Which measurement is the longest?','Tape & Measurement','{"A":"7/16 in","B":"3/8 in","C":"1/2 in","D":"5/16 in"}','C',null,'1/2 = 8/16.'),
('preclass_math','q13',13,'mc','A weld bead must start at 10 7/8 inches. Where is that location on a tape measure divided into 1/16-inch increments?','Tape & Measurement','{"A":"Two small lines before 11 in","B":"One small line after 10 3/4 in","C":"At 10 1/2 in","D":"Halfway between 10 1/2 in and 11 in"}','A',null,'10 7/8 = 10 14/16.'),
('preclass_math','q14',14,'mc','How many 1/8-inch segments are in 1 inch?','Tape & Measurement','{"A":"4","B":"6","C":"8","D":"10"}','C',null,'1 ÷ 1/8 = 8 segments.'),
('preclass_math','q15',15,'mc','True or False: A tape measure marked in 1/16-inch increments divides each inch into 16 equal spaces.','Tape & Measurement','{"A":"True","B":"False"}','A',null,'Sixteen 1/16-inch spaces make one inch.'),
('preclass_math','q16',16,'mc','Five holes are drilled evenly along an 18-inch plate, with the first hole at one end and the last hole at the other end. What is the spacing between adjacent holes?','Layout, Area & Conversions','{"A":"4 in","B":"3.5 in","C":"4.5 in","D":"3.6 in"}','C',null,'Five holes create four equal spaces. 18 ÷ 4 = 4.5 inches.'),
('preclass_math','q17',17,'mc','Steel plate costs $0.30 per square inch. What is the material cost of a 12 in × 6 in piece?','Layout, Area & Conversions','{"A":"$2.10","B":"$18.00","C":"$21.60","D":"$19.50"}','C',null,'72 × $0.30 = $21.60.'),
('preclass_math','q18',18,'mc','A steel rod is 5 feet long. How many inches is that?','Layout, Area & Conversions','{"A":"50","B":"55","C":"60","D":"65"}','C',null,'5 × 12 = 60 inches.'),
('preclass_math','q19',19,'mc','A 36-inch bar is cut into 5 equal sections. What is the length of each section?','Shop Arithmetic','{"A":"6 in","B":"7 in","C":"7.2 in","D":"7.5 in"}','C',null,'36 ÷ 5 = 7.2 inches.'),
('preclass_math','q20',20,'text','What is the decimal equivalent of 9/16 inch?','Fractions & Decimals',null,'0.5625','["0.5625",".5625","0.56250",".56250"]','9 ÷ 16 = 0.5625.'),
('blueprint_day1','d1q1',1,'mc','[Drawing] Refer to the V-Groove Test Block. Why are three views used to show the object?','Day 1','{"A":"To give enough information about shape, size, and features that one view alone cannot show","B":"To show three different material types","C":"To give each welder a separate copy","D":"To avoid using dimensions"}','A',null,null),
('blueprint_day1','d1q2',2,'mc','[Drawing] Which three standard orthographic views are typically shown for the V-Groove Test Block?','Day 1','{"A":"Front, top, and right-side views","B":"Isometric, exploded, and section views","C":"Front, detail, and pictorial views","D":"Top, bill of materials, and note view"}','A',null,null),
('blueprint_day1','d1q3',3,'mc','[Drawing] In standard orthographic projection, which two views show the same length?','Day 1','{"A":"Front and top","B":"Top and right side","C":"Front and right side","D":"Detail and section"}','A',null,null),
('blueprint_day1','d1q4',4,'mc','[Drawing] In standard orthographic projection, which two views show the same width or depth?','Day 1','{"A":"Front and top","B":"Top and right side","C":"Front and right side","D":"Front and detail"}','B',null,null),
('blueprint_day1','d1q5',5,'mc','[Drawing] In standard orthographic projection, which two views show the same height or thickness?','Day 1','{"A":"Front and top","B":"Top and right side","C":"Front and right side","D":"Top and detail"}','C',null,null),
('blueprint_day1','d1q6',6,'mc','[Drawing] What do the top and right-side views have in common with respect to the front view?','Day 1','{"A":"They align with the front view to carry dimensions and features across","B":"They are always drawn larger than the front view","C":"They replace the need for notes","D":"They remove hidden lines from the drawing"}','A',null,null),
('blueprint_day1','d1q7',7,'mc','What is the main purpose of an object line on a print?','Day 1','{"A":"To show visible edges and outlines of the part","B":"To show center points only","C":"To show cutting planes","D":"To show dimensions only"}','A',null,null),
('blueprint_day1','d1q8',8,'mc','What is the main purpose of a hidden line?','Day 1','{"A":"To show edges or features not directly visible in that view","B":"To show the outside shape only","C":"To show the center of a hole","D":"To show a finished weld contour"}','A',null,null),
('blueprint_day1','d1q9',9,'mc','What does a centerline usually indicate?','Day 1','{"A":"The center of a circular or symmetrical feature","B":"The cutting direction for a saw","C":"The surface finish required","D":"The location of a title block"}','A',null,null),
('blueprint_day1','d1q10',10,'mc','What is the job of a dimension line?','Day 1','{"A":"To show the size or distance being measured","B":"To show hidden edges","C":"To show a material break","D":"To show the order of welding"}','A',null,null),
('blueprint_day1','d1q11',11,'mc','What is the job of an extension line?','Day 1','{"A":"To extend from the feature out to the dimension line","B":"To darken object lines","C":"To replace leader lines","D":"To show a weld contour"}','A',null,null),
('blueprint_day1','d1q12',12,'mc','When a drawing includes notes or specifications, why must they be checked before fabrication starts?','Day 1','{"A":"They may include instructions not obvious from the views alone","B":"They are only for office filing","C":"They are used only after welding is complete","D":"They replace all dimensions on the print"}','A',null,null),
('blueprint_day1','d1q13',13,'mc','A general specification placed in or near the title block usually applies to:','Day 1','{"A":"All or several views on the drawing","B":"Only the smallest detail view","C":"Only the welder who signs first","D":"Only one hidden feature"}','A',null,null),
('blueprint_day1','d1q14',14,'mc','On a print, the diameter symbol tells the reader that the dimension refers to:','Day 1','{"A":"The full distance across a circle","B":"Half the distance across a circle","C":"The length of a slot","D":"The angle of a bevel"}','A',null,null),
('blueprint_day1','d1q15',15,'mc','Which statement best describes why dimensions matter to welders and fabricators?','Day 1','{"A":"Wrong dimensions affect fit-up, hole location, and final assembly","B":"Dimensions only matter to machinists","C":"Dimensions are optional if the shape looks right","D":"Dimensions are used only for record keeping"}','A',null,null),
('blueprint_day1','d1q16',16,'mc','If two group members disagree on what a dimension means, the best next step is to:','Day 1','{"A":"Go back to the view, lines, and notes and prove the answer from the print","B":"Choose the answer that sounds fastest","C":"Ignore the dimension and move on","D":"Let the loudest person decide"}','A',null,null),
('blueprint_day1','d1q17',17,'mc','A reference dimension is usually included to:','Day 1','{"A":"Provide extra information without controlling production size","B":"Replace every required tolerance","C":"Show hidden lines more clearly","D":"Identify the drawing revision"}','A',null,null),
('blueprint_day1','d1q18',18,'mc','Which print-reading habit is strongest when learning basic views?','Day 1','{"A":"Compare all views before making a decision","B":"Read only the front view","C":"Ignore notes until the end","D":"Assume every line means the same thing"}','A',null,null),
('blueprint_day1','d1q19',19,'mc','If a hole appears as a circle in one view and as hidden edges in another view, that tells the reader that:','Day 1','{"A":"The feature must be interpreted across more than one view","B":"The print is automatically wrong","C":"The hole is not really there","D":"The dimensions can be ignored"}','A',null,null),
('blueprint_day1','d1q20',20,'mc','Why is it dangerous to rely on one view alone when reading a fabrication print?','Day 1','{"A":"One view rarely shows all surfaces, features, and dimensions clearly","B":"One view always uses the wrong scale","C":"One view cannot contain object lines","D":"One view is only for inspectors"}','A',null,null)
on conflict(assessment_slug,question_key) do nothing;
